server:
  port: 8888
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: autores
              uri: lb://AUTORES
              predicates:
                - Path=/api/v1/autores/**
            - id: reservas
              uri: lb://RESERVAS
              predicates:
                - Path=/api/v1/reservas/**
            - id: salas
              uri: lb://SALAS
              predicates:
                - Path=/api/v1/salas/**
            - id: usuarios
              uri: lb://USUARIOS
              predicates:
                - Path=/api/v1/usuarios/**
            - id: prestamos
              uri: lb://PRESTAMOS
              predicates:
                - Path=/api/v1/prestamos/**
            - id: categorias
              uri: lb://CATEGORIAS
              predicates:
                - Path=/api/v1/categorias/**
            - id: stocks
              uri: lb://STOCKS
              predicates:
                - Path=/api/v1/stocks/**
            - id: multas
              uri: lb://MULTAS
              predicates:
                - Path=/api/v1/multas/**
            - id: libros
              uri: lb://LIBROS
              predicates:
                - Path=/api/v1/libros/**
            - id: roles
              uri: lb://ROLES
              predicates:
                - Path=/api/v1/roles/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"